[project]
name = "streamlit_apps"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "akshare>=1.18.37",
    "python-dotenv>=1.0.0",
    "coloredlogs>=15.0.1",
    "ipykernel>=6.29.5",
    "ipywidgets>=8.1.5",
    "jupyter>=1.1.1",
    "pandas>=2.2.3",
    "plotly>=6.0.0",
    "pytz>=2025.1",
    "streamlit-autorefresh>=1.0.1",
    "streamlit>=1.43.2",
    "mootdx>=0.11.7",
    "eltdx>=3.0.9",
    "tqsdk>=3.10.2",
    "mini-racer>=0.12.4",
    "vectorbt>=1.0.0",
    "pyobjc-framework-cocoa>=12.2.2 ; sys_platform == 'darwin'",
    "pyobjc-framework-applicationservices>=12.2.2 ; sys_platform == 'darwin'",
]
